Azure/aaz-dev-tools

- src/backend/swagger/model/schema/items.py
- src/backend/swagger/model/schema/operation.py
- src/backend/swagger/model/schema/parameter.py
- src/backend/swagger/model/schema/path_item.py
- src/backend/swagger/model/schema/reference.py
- src/backend/swagger/model/schema/response.py
- src/backend/swagger/model/schema/schema.py
- src/backend/swagger/model/schema/swagger.py
- src/backend/swagger/model/schema/x_ms_parameterized_host.py
- src/backend/swagger/model/specs/__init__.py
- src/backend/swagger/model/specs/_swagger_loader.py
- src/backend/swagger/tests/schema_tests/test_schema.py
- src/backend/swagger/tests/schema_tests/test_swagger_link.py
- src/backend/swagger/tests/specs_tests/test_swagger_loader.py
- src/backend/swagger/utils/exceptions.py
1. Support to link reference instance in swagger models.
2. Support to link discriminators.
> Support swagger link

- src/backend/command/model/configuration/_arg.py
- src/backend/command/model/configuration/_command.py
- src/backend/command/model/configuration/_command_group.py
- src/backend/command/model/configuration/_configuration.py
- src/backend/command/model/configuration/_content.py
- src/backend/command/model/configuration/_fields.py
- src/backend/command/model/configuration/_format.py
- src/backend/command/model/configuration/_help.py
- src/backend/command/model/configuration/_http.py
- src/backend/command/model/configuration/_operation.py
- src/backend/command/model/configuration/_output.py
- src/backend/command/model/configuration/_schema.py
1. apply serialize_when_none for most of models. 
2. hide description when call to_primitive.
3. hide stage property when it's stable.
> Json output optimize. 

- src/backend/command/model/configuration/_arg_builder.py
Some schema name may contain $ prefix. Remove $ prefix for arg builder
> Remove $ prefix for arg builder

- src/backend/command/api/editor.py
- src/backend/command/controller/config_editor.py
- src/backend/command/tests/editor_tests/test_workspace.py
Editor workspace will be saved as a folder with ws.json file in it.
> Optimize workspace. 

- src/backend/cli/controller/az_module_manager.py
AzExtensionManager.update_module
> Fix unexpected none return

- HISTORY.rst
- src/aaz_dev/app/app.py
- src/aaz_dev/command/api/editor.py
- src/aaz_dev/command/controller/workspace_cfg_editor.py
- src/aaz_dev/command/controller/workspace_manager.py
- src/aaz_dev/command/model/configuration/_arg.py
- src/aaz_dev/command/model/configuration/_arg_builder.py
- src/aaz_dev/command/model/configuration/_command.py
- src/aaz_dev/command/model/configuration/_content.py
- src/aaz_dev/command/model/configuration/_format.py
- src/aaz_dev/command/model/configuration/_http.py
- src/aaz_dev/command/model/configuration/_http_request_body.py
- src/aaz_dev/command/model/configuration/_instance_update.py
- src/aaz_dev/command/model/configuration/_operation.py
- src/aaz_dev/command/model/configuration/_utils.py
- src/aaz_dev/command/tests/api_tests/test_editor.py
- src/aaz_dev/command/tests/configuration_tests/test_generate_args.py
- src/aaz_dev/swagger/controller/command_generator.py
- src/aaz_dev/swagger/model/schema/response.py
- src/aaz_dev/swagger/model/schema/schema.py
- src/aaz_dev/swagger/model/specs/_resource_provider.py
- src/web/src/theme.tsx
- src/web/src/views/generation/GenerationModuleEditor.tsx
- src/web/src/views/workspace/WSEditor.tsx
- src/web/src/views/workspace/WSEditorCommandArgumentsContent.tsx
- src/web/src/views/workspace/WSEditorCommandContent.tsx
- src/web/src/views/workspace/WSEditorCommandGroupContent.tsx
- src/web/src/views/workspace/WSEditorSwaggerPicker.tsx
- version.py
* Support argument flatten in Workspace Editor
* Optimize error message display
> Support argument flatten

- src/aaz_dev/cli/templates/aaz/command/_cmd.py.j2
- src/aaz_dev/command/model/configuration/_arg_builder.py
1. return nullable for schema base arguments in `update` commands;
2. fix issue in cmd.py template
> Fix more bugs

- src/aaz_dev/cli/controller/az_arg_group_generator.py
- src/aaz_dev/command/controller/specs_manager.py
- src/aaz_dev/command/model/configuration/_arg_builder.py
- src/aaz_dev/docs/Docs/readme.md
- src/web/src/views/workspace/WSEditorCommandArgumentsContent.tsx
- src/web/src/views/workspace/WSEditorCommandContent.tsx
- src/web/src/views/workspace/WSEditorCommandGroupContent.tsx
1. Support `singular_options` for list argument.
2. Correct `summary` word.
> Support `singular_options` by default.

- src/aaz_dev/command/model/configuration/_arg_builder.py
- src/aaz_dev/swagger/model/schema/schema.py
1. Fix nullable issue for discriminators
2. Fix frozen issue for additional props
> Fix more issues

- src/aaz_dev/cli/controller/az_module_manager.py
Wait command only works on the resources which have provisioningState field in get response.
> Wait command generation: add has provisioning state field varification.

- src/aaz_dev/command/controller/workspace_manager.py
- src/aaz_dev/command/model/configuration/_arg_builder.py
- src/aaz_dev/swagger/controller/command_generator.py
- [disable flatten for argument when the schema has cls definition](https://github.com/Azure/aaz-dev-tools/pull/114/commits/a3c900ba8785ec6c7e1fcbc3dcb51fa0c8d445f9)
- [optimize command description when generated from swagger](https://github.com/Azure/aaz-dev-tools/pull/114/commits/7704926cc3ca6b19e19325b6926a5fd24295b617)
- [support examples inherit](https://github.com/Azure/aaz-dev-tools/pull/114/commits/9fe3a3f5a3e6e6550e275b9a14efca540099df47)
> Inherit examples

- src/aaz_dev/command/api/editor.py
- src/aaz_dev/command/controller/cfg_reader.py
- src/aaz_dev/command/controller/workspace_manager.py
- src/aaz_dev/command/model/configuration/_resource.py
- src/aaz_dev/swagger/controller/command_generator.py
- src/aaz_dev/swagger/controller/specs_manager.py
- src/web/src/views/workspace/WSEditor.tsx
- src/web/src/views/workspace/WSEditorCommandContent.tsx
- src/web/src/views/workspace/WSEditorCommandTree.tsx
- src/web/src/views/workspace/WSEditorSwaggerPicker.tsx
- src/web/src/views/workspace/WSEditorToolBar.tsx
> Feature workspace editor reload swagger modification

- HISTORY.rst
- version.py
* Support to parse swagger resource providers without `microsoft` keywords (#116)
* Support swagger modification reload in workspace (#117)
> Release v0.10.1

- src/aaz_dev/command/api/editor.py
- src/aaz_dev/command/controller/workspace_manager.py
- src/web/src/views/workspace/WSEditor.tsx
- src/web/src/views/workspace/WSEditorToolBar.tsx
add workspace rename and delete func
> Workspace modify

- HISTORY.rst
- src/aaz_dev/utils/config.py
- version.py
* Support workspace rename and delete (#123)
* Fix resource folder name 255 length limitation (#124)
> Release v0.10.3

- HISTORY.rst
- version.py
* Support export unregistered command code (#126)
* Refactor CLI Generators (#126)
* Support lifecycle callbacks in generated AAZCommand code (#127)
> Release v0.11.0

- HISTORY.rst
- version.py
* Fix patch only not work in workspace editors (#132)
* Fix UI bugs in CLI generators (#132)
* Fix swagger frozen issue in additional properties (#130)
> release v0.11.1

- src/web/src/views/workspace/WSEditor.tsx
- src/web/src/views/workspace/WSEditorToolBar.tsx
> Add delete confirmation for workspace delete

- HISTORY.rst
- version.py
* Support class type arguments `unwrap` and `flatten` (#145)
* Support resource url filter in swagger picker (#146)
> Release v0.14.0

- src/aaz_dev/command/controller/specs_manager.py
- src/aaz_dev/command/controller/workspace_manager.py
* Remove unlinked command versions in aaz
* Remove empty commands in aaz
* Remove empty command groups in aaz
> Fix workspace export to aaz issue.

- src/aaz_dev/cli/templates/aaz/command/_cmd.py.j2
> Ignore empty confirmation string in generated code.

- src/aaz_dev/command/controller/cfg_reader.py
- src/aaz_dev/command/controller/workspace_cfg_editor.py
- src/aaz_dev/command/model/configuration/_arg.py
- src/aaz_dev/swagger/controller/command_generator.py
- src/aaz_dev/swagger/model/schema/cmd_builder.py
- src/aaz_dev/swagger/model/schema/path_item.py
The class schema implementation will be missed in complicated inherence overwritten, while parse swagger definitions. This PR fixed it.
> Fix class inherence overwritten issue

- src/web/src/views/workspace/WSEditorCommandArgumentsContent.tsx
- src/web/src/views/workspace/WSEditorCommandContent.tsx
> Support to modify argument options for subcommands

- src/aaz_dev/cli/controller/az_selector_generator.py
- src/aaz_dev/cli/templates/aaz/command/_cmd.py.j2
- src/aaz_dev/command/controller/workspace_cfg_editor.py
Disable requirement for index in subcommand create commands. Support new index auto generation.
> Feature support array index auto generate

- src/aaz_dev/cli/controller/az_arg_group_generator.py
- src/aaz_dev/cli/controller/az_command_generator.py
Disable id-part for create command and subcommands
> control id part property for argument

- src/aaz_dev/command/model/configuration/_http.py
fix bugs to setup id_part for path like                 "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/applicationGateways/{applicationGatewayName}/start"
> fix bugs to setup id_part

- HISTORY.rst
- version.py
* Ignore argument id-parts when generate code for list commands (#169)
* Optimize swagger `Error response` invalid hints (#170)
> Release v0.16.1

- HISTORY.rst
- version.py
* Fix subresource selector in generic update operation (#172)
> release v0.16.2

- src/aaz_dev/app/run.py
- src/aaz_dev/command/api/config.py
- src/aaz_dev/command/api/editor.py
- src/aaz_dev/command/controller/workspace_manager.py
- src/aaz_dev/command/model/configuration/_resource.py
- src/aaz_dev/command/tests/configuration_tests/test_xml.py
- src/aaz_dev/swagger/api/specs.py
- src/aaz_dev/swagger/controller/specs_manager.py
- src/aaz_dev/swagger/model/specs/__init__.py
- src/aaz_dev/swagger/model/specs/_swagger_specs.py
- src/aaz_dev/utils/config.py
- src/web/src/views/workspace/WSEditorSwaggerPicker.tsx
> Workspace swagger picker supports load default swagger module and resource providers.

- src/web/src/views/workspace/WSEditorCommandContent.tsx
> Fix Workspace show no argument commands

- HISTORY.rst
- src/aaz_dev/utils/config.py
- version.py
0.18.0
++++++
* Relink command after class unwrapped (#182)
* Support unwrap class modification inherit (#181)
* Change portal namespace (#179)
> Release v0.18.0

- src/aaz_dev/cli/api/az.py
- src/aaz_dev/cli/controller/az_atomic_profile_builder.py
- src/aaz_dev/cli/controller/az_module_manager.py
- src/aaz_dev/cli/controller/az_profile_generator.py
- src/aaz_dev/cli/model/common/_fields.py
- src/aaz_dev/cli/model/view/_command.py
- src/aaz_dev/cli/model/view/_command_group.py
- src/web/src/views/cli/CLIModGeneratorProfileCommandTree.tsx
- src/web/src/views/cli/CLIModuleCommon.tsx
- src/web/src/views/cli/CLIModuleGenerator.tsx
Support generate edited commands in the module. This will speed up the generation for a large module such as `network`.
> Support partial commands generation in a module.

- src/web/src/views/workspace/WSEditorCommandArgumentsContent.tsx
> Fix array arguments element type display issue

- src/aaz_dev/cli/api/_cmds.py
--cli-path and --cli-extension-path. Change second instance of --cli-path to --cli-extension-path
> Fix incorrect statement when checking for content in

- HISTORY.rst
- src/aaz_dev/utils/config.py
- version.py
1.0.0
++++++
* GA release
* Add FAQ for LRO missing response defination (#217)
* Add OpenAPI link for LRO response (#218)
* Flatten properties named property by default only when it has sub properties. (#219)
* Fix bug in classify error format (#220)
* Support title property in swagger definition (#221)
> GA Release v1.0.0

- HISTORY.rst
- version.py
* Fix generated code issue for class arguments (#224)
> Release v1.0.1

- .github/azure-client-tools-bot/config.yml
> {CI} Support version release notification to teams

- src/aaz_dev/swagger/model/schema/cmd_builder.py
- src/aaz_dev/swagger/model/schema/operation.py
- src/aaz_dev/swagger/model/schema/x_ms_long_running_operation.py
- src/aaz_dev/swagger/tests/schema_tests/test_schema.py
Resolve: https://github.com/Azure/aaz-dev-tools/issues/214
> support lro final-state-schema

- HISTORY.rst
- version.py
1.1.1
++++++
* Support x-ms-long-running-operation-options.final-state-schema of swagger (#237)
> release v1.1.1

- src/aaz_dev/cli/controller/az_arg_group_generator.py
- src/aaz_dev/cli/templates/aaz/command/_cmd.py.j2
- src/aaz_dev/command/controller/workspace_cfg_editor.py
- src/aaz_dev/command/model/configuration/__init__.py
- src/aaz_dev/command/model/configuration/_arg.py
- src/aaz_dev/command/model/configuration/_arg_builder.py
- src/web/src/views/workspace/WSEditorCommandArgumentsContent.tsx
> Support argument prompt input

- HISTORY.rst
- version.py
* Support x-typespec-name and x-typespec-generated in swagger (#243)
> Release v1.2.1

- HISTORY.rst
- version.py
1.3.0
++++++
* Support TimeSchema and TimeArg (#250)
* Support `summary` field for swagger operation (#249)
> Release v1.3.0

- HISTORY.rst
- version.py
* Rewrite the workspace editor doc (#253)
* Refactor the github page for docs (#254)
* Adjust layout for small screen displays. (#255)
* Update faq.md (#256)
> Release v1.3.1 

- HISTORY.rst
- version.py
* Improve Docs of CLI Generator (#258)
* Improve doc display (#259)
* [Doc] Add note for examples (#260)
* Update generation template for pagination (#261)
* Change the initial extension version to 1.0.0b1 (#263)
> Release v1.4.0

- HISTORY.rst
- version.py
1.5.2
++++++
* Update docs for Command Usage and Testing (#270)
* Fix bugs while command has no arguments (#271)
* Add docs for subcommand generation (#272)
> Release v1.5.2

- HISTORY.rst
- docs/_config.yml
- version.py
* Adding `profile_` prefix for azure stack profile in CLI aaz package (#274)
> Release v1.6.0

- HISTORY.rst
- src/aaz_dev/utils/config.py
- version.py
1.6.2
++++++
* Convert int value to float for FloatArg default and blank value (#279)
> release 1.6.2

- HISTORY.rst
- docs/_config.yml
- version.py
1.7.1
++++++
* Fix bug when generate property name with special characters in code (#284)
> Release v1.7.1

- src/aaz_dev/cli/controller/az_command_generator.py
- src/aaz_dev/command/api/editor.py
- src/aaz_dev/command/api/specs.py
- src/aaz_dev/command/controller/workspace_manager.py
- src/aaz_dev/command/model/editor/_workspace.py
- src/aaz_dev/swagger/controller/command_generator.py
- src/aaz_dev/swagger/controller/specs_manager.py
- src/aaz_dev/swagger/tests/common.py
- src/aaz_dev/utils/plane.py
- src/web/src/views/workspace/WSEditorSwaggerPicker.tsx
- src/web/src/views/workspace/WorkspaceSelector.tsx
When create a workspace, the response provider should be specified. And it can only add resources in that resource provider.
This change is for the future support of data-plane.
> Limit a workspace to one resource provider only.

- HISTORY.rst
- docs/_config.yml
- version.py
2.0.0
++++++
* Limit a workspace to one resource provider only. (#290)
> Release v2.0.0
