src/backend/command/model/configuration/__init__.py, src/backend/command/model/configuration/_arg.py, src/backend/command/model/configuration/_content.py, src/backend/command/model/configuration/_http.py, src/backend/command/model/configuration/_http_request_body.py, src/backend/command/model/configuration/_http_response_body.py, src/backend/command/model/configuration/_instance_update.py, src/backend/command/model/configuration/_schema.py, src/backend/swagger/controller/command_generator.py, src/backend/swagger/model/schema/operation.py, src/backend/swagger/model/schema/parameter.py, src/backend/swagger/model/schema/response.py
1. Change the order for model multiple inheritance. Because in Schematic library, the fields inherited from bases are overwritten reversed:
```python
for base in reversed(bases):
if hasattr(base, '_schema'):
fields.update(deepcopy(base._schema.fields))
options_members.update(dict(base._schema.options))
validator_functions.update(base._schema.validators)
````
2. Add CMDArgBaseField
3. Use `CMDRequestJson` and `CMDResponseJson` instead of `CMDJson`
4. Use `CMDHttpRequestBody` and `CMDHttpResponseBody` instead of `CMDHttpBody`
5. Use `CMDHttpRequestJsonBody` and `CMDHttpResponseJsonBody` instead of `CMDHttpJsonBody`
=> Fix configuration model issues

HISTORY.rst, src/aaz_dev/app/run.py, version.py
* Support `--quiet` argument in aaz-dev run to disable web browser page opening.
* Raise error when port is used by others.
=> Optimize `aaz-dev run` command

src/aaz_dev/command/model/configuration/_arg_builder.py
The` singular options` for list argument should be used in limited scopes, for example, to compatible with existing commands.
=> Disable `singular option` generation for list argument by default

src/aaz_dev/cli/controller/az_command_generator.py
azure-cli-core/aaz not support paging for long running command. So disable it right now.
=> Disable paging for long running command

HISTORY.rst, src/aaz_dev/utils/config.py, version.py
* Limit minimal python version to 3.8 (#98)(#99)(#101)
* Fix issue when rename commands in cfg_editor (#100)
* Remove python-Levenshtein reliance (#102)
* Disable paging for long running commands (#103)
* Add provisioning state field verification in wait command generation (#104)
=> release v0.9.5

HISTORY.rst, version.py
* Fix cls argument base inherent (#136)
* Fix reload swagger error if no arg change previously (#135)
* Add delete confirmation for workspace delete (#134)
=> Release v0.11.2

src/aaz_dev/swagger/model/schema/cmd_builder.py
read_only not inherent between CMDBuilders, it will cause problem for class reference between read_only class reference and none-readonly class
=> [Swagger] fix read_only inherent issue.

HISTORY.rst, src/aaz_dev/utils/config.py, version.py
* Disable Read only inherent in swagger translators (#139)
* Enable register_callback decorator (#129)
=> release-v0.12.0

HISTORY.rst, version.py
0.13.0
++++++
* Support free from dict for `"additionalProperties":True` swagger definition (#138)
* Support command confirmation prompt modification (#141)
* Fix duplicated option names detect when flatten argument (#142)
* Fix reload swagger aug group name overwrite (#143)
=> Release v0.13.0

HISTORY.rst, src/aaz_dev/utils/config.py, version.py
* Fix workspace export to aaz issue. (#148)
* Ignore empty confirmation string in generated code. (#149)
* Fix version and readiness parse issue in swagger file path (#150)
* Fix class inheritance overwritten issue (#151)
=> release v0.15.0

HISTORY.rst, version.py
0.15.1
---
* Fix `workspace` bug on class argument unwrap (#155)
* Fix `workspace` reload issue for update command using patch (#156)
* Optimize `generation` error message display when loading modules (#157)
=> Release v0.15.1

HISTORY.rst, src/aaz_dev/utils/config.py, version.py
- Support build-in keywords in property name generation (#167)
- Add portal CLI generator (#153)
- Support to generate property name starts with digit (#166)
- Support to modify default for array, dict and object arguments (#165)
- Fix `id_part` setup (#164)
- Disable `id_part` for create command and subcommand (#163)
- Support array index auto generate (#162)
- Support to modify argument options for subcommand (#161)
- Support subcommand generation (#154)
- Add FAQs for Swagger definition (#160)
- Fix `x-ms-skip-url-encoding` unparsed in Swagger (#159)
=> Release v0.16.0

src/aaz_dev/command/model/configuration/_schema.py
Accord to [x-ms-identifiers design](http://azure.github.io/autorest/extensions/#x-ms-identifiers), it's possible to add '/' character in elements to inner property. It's not supported in aaz-dev-tools. So ignore them.
=> ignore `x-ms-identifiers` with '/' character

HISTORY.rst, version.py
0.17.0
----
* Workspace swagger picker supports load default swagger module and resource providers (#175)
* `aaz-dev run`: Add `--swagger-module-path`, "--module", "--resource-provider" to specify single swagger repo for code generation (#175)
* `aaz-dev command-model generate-from-swagger`: Support generate command model from swagger by readme tag for pipeline use (#176)
* `aaz-dev cli generate-by-swagger-tag`: Support generate code in cli from command models by using readme tag for pipeline use (#178)
* `aaz-dev regenerate`: Support to regenerate aaz commands from command models (#178)
* Fix Workspace display no arguments command error (#177)
* Ignore '/' character in x-ms-identifiers swagger property (#174)
=> Release v0.17.0

requirements.txt
azure-cli does not support [python 3.11](https://github.com/Azure/azure-cli/issues/24494), update requirements first.
=> update requirements to support Python 3.11

HISTORY.rst, src/aaz_dev/utils/config.py, version.py
* Feature support subcommand modification inheritance (#184)
* Fix _iter_schema_in_json when js has not schema (#185)
* Update requirements to support Python 3.11 (#186)
* Inherent subresource commands in aaz when export workspace (#187)
* Support partial commands generation in a module (#189)
=> Release v0.19.0

HISTORY.rst, version.py
0.19.3
++++++
* Support default error format for mgmt-plane API (#202)
=> Release v0.19.3

HISTORY.rst, version.py
* Fix incorrect statement when checking for content in --cli-path and --cli-extension-path (#205)
* Fix bug when merge sub resources in aaz (#206)
* Support inherent argument hide property on flatten (#207)
* Fix bug for string type output commands (#209)
* Fix sub command inherit bugs (#211)
=> Release v0.20.0

src/aaz_dev/swagger/model/schema/parameter.py
Fix bug when loading swagger resource which has no description for path parameters.
=> Add `title` field support for parameter in swagger.

src/aaz_dev/command/controller/cfg_reader.py
=> Fix bugs while command has no arguments.

src/aaz_dev/cli/controller/az_module_manager.py, src/aaz_dev/cli/controller/az_operation_generator.py, src/aaz_dev/cli/controller/az_profile_generator.py, src/aaz_dev/cli/model/atomic/_profile.py, src/aaz_dev/cli/model/view/_profile.py, src/aaz_dev/utils/case.py
Depend on the change in https://github.com/Azure/azure-cli/pull/27073
=> Adding 'profile_' prefix for azure stack profile

src/aaz_dev/cli/controller/az_operation_generator.py, src/aaz_dev/command/controller/cfg_reader.py, src/aaz_dev/command/controller/workspace_cfg_editor.py, src/aaz_dev/command/model/configuration/_arg_builder.py, src/aaz_dev/command/model/configuration/_schema.py
Support discriminator value which contains special characters like [Microsoft.Compute/virtualMachines](https://github.com/Azure/azure-rest-api-specs/blob/d247207c59848d06facf8a7b4f884e356205c15c/specification/resourcemover/resource-manager/Microsoft.Migrate/stable/2022-08-01/resourcemovercollection.json#L1933)
=> Fix bug when special characters appreared in discription value

src/aaz_dev/cli/controller/az_arg_group_generator.py, src/aaz_dev/command/controller/specs_manager.py, src/aaz_dev/command/controller/workspace_cfg_editor.py, src/aaz_dev/command/model/configuration/_arg.py, src/aaz_dev/command/model/configuration/_arg_builder.py, src/web/src/views/workspace/WSEditorCommandArgumentsContent.tsx
Support set configuration key in argument, which is used to retrieve default value from cli configurations.
Related change in azure-cli-core: https://github.com/Azure/azure-cli/pull/27205
=> Support configuration key

src/aaz_dev/swagger/model/schema/parameter.py
For some APIs, the body parameter is **required** but all its properties are **read only**. Like this [swagger parameter](https://github.com/Azure/azure-rest-api-specs/blob/efbe157d69f1909baf2b866cc82df8e0093f533b/specification/vmware/resource-manager/Microsoft.AVS/stable/2023-03-01/vmware.json#L1450-L1458). In that case, we still need to pass an **empty** JSON object.
=> Support to pass an empty request body when it's required.
